export const FETCH_QUIZ_START = 'FETCH_QUIZ_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR'

export const GET_ANSWER_RESULT = 'GET_ANSWER_RESULT'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const GO_TO_NEXT_QUESTION = 'GO_TO_NEXT_QUESTION'
export const REPEAT_QUIZ = 'REPEAT_QUIZ'

export const CREATE_NEW_QUESTION = 'CREATE_NEW_QUESTION'
export const RESET_QUIZ = 'RESET_QUIZ'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const CLOSE_MENU = 'CLOSE_MENU'
export const TOGGLE_MENU = 'TOGGLE_MENU'






